# Generated by Django 5.2.2 on 2025-06-17 11:37

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('given', 'Given')], default='available', max_length=10)),
                ('cover_image', models.ImageField(default='covers/default.jpg', upload_to='covers/', validators=[books.models.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(blank=True, default='UNKNOWN', max_length=13)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('interested_users', models.ManyToManyField(blank=True, related_name='interested_books', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_books', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
                ('pickup_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.pickuplocation')),
            ],
        ),
    ]
